import React, {useEffect, useState} from "react";

import "../../style/Product.scss";
import {buyProductNow, getOwnerData} from "../../service/ProductService";
import styled from "@emotion/styled";
import {useHistory} from "react-router-dom";

export const FailedBuyMP = () => {

    const product = JSON.parse(localStorage.getItem("mpBuy"))
    const history = useHistory();


    return(
        <Wrapper>
            <Fail/>
            <Title>No pudimos procesar tu pago</Title>
            <Subtitle>
                Volvé a intentar con otro medio de pago!
            </Subtitle>
            <Button onClick={() => history.push('/product/'+ product.id)}>Cambiar medio de pago</Button>
        </Wrapper>)
};

const Wrapper = styled.div`
    background: white;
    min-width: fit-content;
    min-height: fit-content;
    border-radius: 50px;
    max-width: fit-content;
    max-height: fit-content;
    margin-left: 44em;
    margin-top: 10em;
    padding-bottom: 2em;
    padding-top: 2em;
`
const Subtitle = styled.div`
    margin-bottom: 1em;
    margin-right: 2em;
    margin-left: 2em;
`
const Title = styled.div`
    text-align: center;
    font-size: 20px;
    padding: 1em;
`

const Fail = styled.div`
    width: 12em;
    height: 11em;
    margin-left: 4.5em; 
    background-repeat: no-repeat;
    background-image: url("data:image/svg+xml,%3Csvg xml:space='preserve' viewBox='0 0 100 100' y='0' x='0' xmlns='http://www.w3.org/2000/svg' id='圖層_1' version='1.1' width='200px' height='200px' xmlns:xlink='http://www.w3.org/1999/xlink' style='width:100%25;height:100%25;background-size:initial;background-repeat-y:initial;background-repeat-x:initial;background-position-y:initial;background-position-x:initial;background-origin:initial;background-image:initial;background-color:rgb(255, 255, 255);background-clip:initial;background-attachment:initial;animation-play-state:paused' %3E%3Cg class='ldl-scale' style='transform-origin:50%25 50%25;transform:rotate(0deg) scale(0.8, 0.8);animation-play-state:paused' %3E%3Cpath d='M22 78l56-56' stroke-miterlimit='10' stroke-width='16' stroke='%23e15b64' fill='none' style='stroke:rgb(225, 91, 100);animation-play-state:paused' %3E%3C/path%3E%3Cpath d='M78 78L22 22' stroke-miterlimit='10' stroke-width='16' stroke='%23e15b64' fill='none' style='stroke:rgb(225, 91, 100);animation-play-state:paused' %3E%3C/path%3E%3Cmetadata xmlns:d='https://loading.io/stock/' style='animation-play-state:paused' %3E%3Cd:name style='animation-play-state:paused' %3Efail%3C/d:name%3E%3Cd:tags style='animation-play-state:paused' %3Eerror,warning,danger,cross,times,delete,remove,drop,fail,form%3C/d:tags%3E%3Cd:license style='animation-play-state:paused' %3Efree%3C/d:license%3E%3Cd:slug style='animation-play-state:paused' %3Ejxjyiv%3C/d:slug%3E%3C/metadata%3E%3C/g%3E%3C!-- generated by https://loading.io/ --%3E%3C/svg%3E");
`

const Button = styled.button`
    border: none;
    background: lightblue;
    border-radius: 7px;
    padding: 8px;
    margin-top: 1em;
    margin-left: 5em;
`
